name: Motherfucking Form
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
url: http://motherfuckingforms.com
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]